name: Instagram Post Bot

on:
  #workflow_dispatch:   # executa manualment (per provar)
  schedule:
    - cron: "0 8 * * *"  # cada dia a les 08:00 UTC
  workflow_dispatch:     # també manual

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        env:
          IG_USERNAME: ${{ secrets.IG_USERNAME }}
          IG_PASSWORD: ${{ secrets.IG_PASSWORD }}
        run: |
          python post_instagram.py
